"""Workflow schemas."""

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, Field


class WorkflowStep(BaseModel):
    """Schema for a workflow step."""

    id: str
    type: Literal["llm", "tool", "condition", "parallel"]
    title: str
    input: dict[str, Any] = Field(default_factory=dict)
    uses: str | None = None  # Tool name or model
    output_key: str | None = None


class WorkflowSpec(BaseModel):
    """Schema for workflow specification (generated by LLM)."""

    name: str
    version: str = "1.0"
    steps: list[WorkflowStep]


class WorkflowMetaResponse(BaseModel):
    """Schema for workflow metadata response."""

    id: str
    chat_id: str
    temporal_workflow_id: str
    name: str
    status: str  # pending | running | completed | failed
    spec: dict[str, Any]
    steps_status: dict[str, str]
    created_at: datetime
    updated_at: datetime

    model_config = {"from_attributes": True}
